name: Frontend deploy                    # Workflow 이름

on:                                  # Event 감지
  push:
    branches:
      - main
    paths:
      - 'Front/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Front/**'
      
jobs:                                # Job 설정
  frontend:
    name: CI with Node
    runs-on: ubuntu-latest
    env:
      working-directory: ./Front
      
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v2
      
      - name: Check Node v            # Node v 확인
        run: node -v

      - name: Install Dependencies    # 의존 파일 설치
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Build                   # React Build
        run: npm run build
        working-directory: ${{ env.working-directory }}
        
      - name: Deploy S3                 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_FRONT }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_FRONT }}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://pickmoviebucket
        working-directory: ${{ env.working-directory }}
