name: Frontend deploy                    # Workflow 이름

on:                                  # Event 감지
  push:
    branches:
      - main
    paths:
      - 'Front/**'
      
jobs:                                # Job 설정
  frontend:
    name: CI with Node
    runs-on: ubuntu-latest
    env:
      working-directory: ./Front
      
    steps:
      - name: Checkout source code.   # Repo checkout
        uses: actions/checkout@v2
      
      - name: Check Node v            # Node v 확인
        run: node -v
        
      - name: Cache node modules
        uses: actions/cache@v1
        with:
           path: node_modules
           key:
              ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
           restore-keys: # 일치하는 캐시 key가 없을 경우 -> 캐싱 폴더 찾음
              ${{ runner.OS }}-build- ${{ runner.OS }}-

      - name: Install Dependencies    # 의존 파일 설치
        run: npm install
        working-directory: ${{ env.working-directory }}

      - name: Build                   # React Build
        run: npm run build
        working-directory: ${{ env.working-directory }}
